/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#e0c29a',
        'secondary-container': '#fddeb4',
        'background': '#fff8f4',
        'on-secondary-fixed-variant': '#584325',
        'tertiary-fixed': '#ffdbd0',
        'primary-container': '#5c161e',
        'outline': '#877272',
        'tertiary-container': '#422a22',
        'on-tertiary-container': '#b39085',
        'tertiary-fixed-dim': '#e5beb2',
        'on-tertiary-fixed-variant': '#5c4037',
        'surface-dim': '#ead7c6',
        'on-primary-container': '#de7b7f',
        'surface-variant': '#f3dfce',
        'primary-fixed-dim': '#ffb3b4',
        'primary-fixed': '#ffdada',
        'secondary-fixed': '#fddeb4',
        'surface-container-low': '#fff1e7',
        'surface-container-high': '#f9e5d4',
        'secondary': '#715b3a',
        'surface-container': '#ffead9',
        'outline-variant': '#dac1c0',
        'on-surface': '#241a10',
        'surface': '#fff8f4',
        'surface-tint': '#984449',
        'on-background': '#241a10',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'inverse-surface': '#3a2e23',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-bright': '#fff8f4',
        'inverse-on-surface': '#ffeee0',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#281901',
        'primary': '#5c161e',
        'on-error': '#ffffff',
        'surface-container-highest': '#f3dfce',
        'on-secondary-container': '#78613f',
        'inverse-primary': '#ffb3b4',
        'tertiary': '#2b160e',
        'on-primary-fixed': '#40010b',
        'on-surface-variant': '#544242',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#2b160f',
        'on-primary-fixed-variant': '#7a2d33',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': 'clamp(1.5rem, 1.1rem + 2vw, 3rem)',
        'gutter': '24px',
        'stack-md': 'clamp(1rem, 0.85rem + 0.75vw, 1.5rem)',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'stack-xl': 'clamp(2rem, 1.3rem + 4vw, 5rem)',
      },
      fontFamily: {
        'display-lg': ['"Playfair Display"', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
